.travis.yml

Travis CI for deploying to the PaaS. Already used in [alphagov/reliability-engineering](https://github.com/alphagov/reliability-engineering/commit/02116f30167fd3f7c6aa49c33005ebe00a4be344). Tested successfully in https://travis-ci.org/alphagov/re-team-manual/builds/402241252

Travis CI for deploying to the PaaS

---

source/documentation/observe-support.md

This PR describes the alerts that we have set up for prometheus and some of the the things to consider when the alert is triggered. These new sections will be referenced by the alert when delivered.
This is just the start and we aim to improve on this as we encounter more of these issues.

Add runbook for alerts

---

source/documentation/observe-support.md

Some of our alerts will create tickets on a Zendesk queue so checking Zendesk will be another task of the interruptible person.

Add zendesk check to observe tasks

---

source/documentation/observe-support.md

- Adds documentation for what you should do on support if a user asks for grafana permissions to be added/updated
- Adds all tasks into a `runbook` section as these previously felt split over several sections

Grafana permissions

---

source/documentation/operational-tasks.md

- this stuff should be in ~/.aws/config, not ~/.aws/credentials
- the gds-users-admin profile was missing (this section duplicates
the re-infra-release-automation README which was correct)

fixes to aws-accounts docs

---

source/documentation/using-re-jenkins.md
source/joiners-and-leavers.html.md.erb
source/observe-support.html.md.erb
source/operational-tasks.html.md.erb
source/using-re-jenkins.html.md.erb

Brief description of the Terraform code we provide to provision a Jenkins and the instance running for teams in TechOps.
It is mostly a pointer to the documentation in the repos, so as to avoid duplicating docs.
We also needed to increment the weight of the subsequent pages.
with @samjamcul

Add documentation about RE Jenkins

---

source/documentation/observe-support.md

Add additional info on actions to take in order to resolve the alert.
As we are suggesting to the interruptible to update the terraform code this will mean that all EBS volumes will be increased.
The reason we are doing this is because if we increase just one EBS volume outside of terraform, this will cause  a problem with applying terraform as it will attempt to decrease the EBS volume size to the terraform size. 
We could target a particular instance but this will mean a bit more work for the interruptible to add logic in the terraform to target a particular instance. Downside of this is that after the EBS volume is increased each instance will need to be `ssh` into in order to update the filesystem disk space.
https://trello.com/c/7DBMMFJh/650-write-instructions-in-the-re-observe-runboo …

Add info to runbook on Prom disk space filling

---

source/documentation/observe-support.md

Started as https://trello.com/c/thV8SLyW/687-ship-logs-to-logit-aws to add links to prometheus logs but I noticed several bits of information was old or could be improved so I also did this at the same time.
- Tidys up content pointing to alert definitions
- Updates content since our move from ECS Prometheus to EC2
Prometheus
- Add further detail to some alerts
- Remove unuseful detail from some alerts
- Adds links to Prometheus logs where appropriate

Update the observe alerts with extra detail and better clarity

---

source/documentation/observe-support.md

We set our calendars up in Pagerduty now, so we don't need to manually
update the contact number.

update observe handover process

---

config/tech-docs.yml

In a recent PR https://github.com/alphagov/re-team-manual/pull/53
I added further level headings to the alerts section of the
observe playbook. As the `max_toc_heading_level` is 6 it means that
all of these headings are added to the navigation. I don't think
this is particularly useful and clutters up the navigation menu.
I have reduced the number down to 3 and I think this gives a
useable menu whilst still providing enough depth to our navigation
so users can find what they want.
This hasn't been tested with users but is just based on what
I think looks sensible.

Change `max_toc_heading_level` from 6 to 3

---

source/architectural-decisions.html.md.erb
source/documentation/architecture/decisions/0001-environments.md
source/documentation/architecture/decisions/0002-configuration-management.md
source/documentation/architecture/decisions/0003-use-ecs-for-initial-beta-buildout.md
source/documentation/architecture/decisions/0004-cloudwatch-metrics.md
source/documentation/architecture/decisions/0005-giving-users-prometheus-access.md
source/documentation/architecture/decisions/0006-deploying-prometheus-to-private-networks-in-aws.md
source/documentation/architecture/decisions/0007-use-ubuntu-18-04.md
source/documentation/architecture/decisions/0008-use-of-verify-egress-proxies.md
source/documentation/architecture/decisions/0009-use-cloud-init-to-build-prometheus-server.md
source/documentation/architecture/decisions/0010-packaging-node-exporter-as-deb-for-verify.md
source/documentation/architecture/decisions/0011-sli-for-how-reliably-do-we-deliver-pages.md
source/documentation/architecture/decisions/0012-deploy-alertmanager-to-k8s.md
source/documentation/architecture/decisions/header.md
source/documentation/prometheus-for-paas-support.md
source/observe-support.html.md.erb
source/prometheus-for-gds-paas-users.html.md.erb

This better reflects the team structure going into next quarter
This Pr also moves the Architectural decision records from monitoring-doc which means that we can archive the monitoring doc
https://trello.com/c/6a84sEpd/803-migrate-adrs-to-re-team-manual
https://trello.com/c/loV2aljk/804-create-rename-re-team-manual-section-for-prometheus-for-gds-paas-users
This necessitates some changes to the alert config 
https://github.com/alphagov/prometheus-aws-configuration-beta/pull/255

Namespace the ex-observe stuff appropriately

---

source/documentation/prometheus-for-paas-support.md

https://trello.com/c/qQpocAVE/797-document-what-we-care-about-operationally-to-ensure-a-good-service
The first commit is a tidy up and the second commit gets down to the ticket.
Note, my approach on `the lack of monitoring of the ip safelist service` as mentioned in the ticket is not to talk about the lack of monitoring of our part of our system but instead talk about it at the top level user need which is that Prometheus can scrape our users /metrics page. After we create an SLI for this then we can decide which parts of our system we should measure.
I also didn't include why we chose our support hours because I don't really know (apart from that we didn't want to because that takes effort) but I can't validate that as a decision driven by our users expectations of reliability.

Document what we care about operationally to ensure a good service

---

source/documentation/prometheus-for-gds-paas/index.md

We no longer use pingdom; we rely on cronitor to tell us if our whole
alerting system is broken.

delete references to pingdom in prometheus pages

---

source/documentation/using-re-jenkins.md
source/using-re-jenkins.html.md.erb

Jenkins within RE has been deprecated.  This PR removes documentation mentioning its use.

Remove all references to the recently deprecated RE Jenkins

---

manifest.yml

- `cflinuxfs3` is the new version that all apps will move to soon.
- Seeing:
```
Deprecation warning: Use of 'buildpack' attribute in manifest is
deprecated in favor of 'buildpacks'. Please see
http://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#deprecated
for alternatives and other app manifest deprecations. This feature
will be removed in the future
```
was annoying.

Upgrade the CF stack to cflinuxfs3 and fix syntax deprecation warning

---

source/documentation/prometheus-for-gds-paas/index.md

Meshing is now fixed and the alertmanagers live in Fargate and not ECS.
Single: matthewcullum-gds

Correct alertmanager details.

---

source/documentation/prometheus-for-gds-paas/index.md

The gds-prometheus-targets bucket is no longer used; instead we use
govukobserve-targets-production, which lives in a different AWS
account.

update references to observe targets bucket

---

source/documentation/performance-platform.md
source/performance-platform.html.md.erb

@tlwr wrote some docs about the Performance Platform for Autom8, but they were buried them so when we had an incident we couldn't find them. Move them here to increase the chance that we will in future.

Migrate docs about the Performance Platform

---

source/documentation/yubikeys.md

The YubiKeys are used to perform SSH by the Pay team. There is no reason
not to document and promote that behaviour across GDS.
- Read through the docs
- Attempt to set up the key

Document the use of SSH with YubiKeys

---

source/documentation/verify.md

- In v0.21.0
([CHANGELOG](https://github.com/alphagov/gds-cli/releases/tag/v1.21.0)),
the `govuk-production` role name was updated to reflect that it's an
`admin` role. Users now need to `gds aws govuk-production-admin -e`.

Update `gds aws` GOV.UK production admin role name in Verify DNS docs

---

source/documentation/prometheus-for-gds-paas/index.md

- Reference the gds-cli, we don't need to have manual role config any
more.
- Don't reference this manual inside a doc in it - we're already reading
it.

Update the Prometheus for PaaS docs further

---

source/documentation/re-oncall-escalation-info.html.md

Add documentation for folks on the RE on-call escalations rota in
PagerDuty. This is intended as a place for folks on the RE on-call
escalations rota to find information on what to do in various situations
and as a place to find important contact information.

Add RE on-call escalation documentation

---

source/documentation/notify.md
source/notify.html.md.erb

Documents a base set of tasks for supporting Notify:
* Accessing metrics
* Accessing logs
* Testing email/sms
* Rolling AMIs
* Running Ansible
The documentation is an expanded form of the notes I took at the [Notify Game Day session](https://hackmd.cloudapps.digital/SkCAz-KFT3qGFT5QaSybkw).

Notify support documentation

---

source/documentation/gds-aws-account-management.md

This changed in the following commit:
https://github.com/alphagov/re-infra-release-automation/commit/d31173f376333800033cbc4e947d4347424ab404

Update documentation with the new role to assume

---

source/documentation/yubikeys.md

- GOV.UK are starting to use Yubikeys (:tada:) for GPG and SSH keys.
- Turns out that this guide uses the defaults (2048), which, when people
use the authentication key portion for SSH add add it to GOV.UK's Puppet
repo, [CI checks fail due to low key
strength](https://github.com/alphagov/govuk-puppet/blob/b588e4ade996e97b8975e69cb00800521fff4a48/modules/users/spec/classes/users_spec.rb#L43-L61).

YubiKey: Specify how to generate 4096-bit GPG keys

---

source/documentation/yubikeys.md

To be consistent with earlier instructions to use a key strength of
4096, update the instructions for publishing the public key to reference
`rsa4096` rather than `rsa2048`.

Replace rsa2048 with rsa4096 in Key ID instructions

---

source/documentation/performance-platform.md

We've not investigated _why_ this happens but this is something we've
done that resolves the problem _when_ it happens.

Add a mitigation for BIG EDIT breaking

---

source/documentation/prometheus-for-gds-paas/index.md.erb

**Why**
Following an incident review of an Observe incident, one recommendation was to improve information around the alert RE_Observe_No_FileSd_Targets.
**What**
This change adds a warning that the alert could be disk space or volume related.

update the runbook with a disk space message to aid diagnosis

---

source/documentation/automate-on-call-interruptible.md
source/documentation/prometheus-for-gds-paas/index.md.erb

We have changed how we deploy alertmanager - it's now multiple A
records on the same domain, not three different domains.

Change docs to point to new alertmanagers

---

source/documentation/yubikeys.md

* Show how to use an existing Yubikey with a GPG key set up on a new laptop.
* Document use with AWS - in particular, avoid U2F.
* Point out not to use pinentry-mac if not on a Mac.

Various improvements to Yubikey docs

---

source/documentation/automate-on-call-interruptible.md

DCS now runs in AWS on GSP. Update the docs to reflect this.
Also removed the docs for making `govuk-dns` changes--these were only
required for doing a DCS failover between Carrenza and UKCloud which is
no longer a thing that can be done.

Update DCS docs after if has moved to GSP

---

source/documentation/automate-on-call-interruptible.md

verify: pipelines moved to big-concourse

---

source/documentation/automate-on-call-interruptible.md

Following https://github.com/alphagov/tech-ops/pull/138 and co.

Remove references to Concourse pipelines that are now automagically generated

---

.secrets.baseline
source/documentation/prometheus-for-gds-paas/index.md.erb

We've binned the old NLB and reverted back to the old old ALB design.

Update alertmanager documentation to match new ALB

---

source/documentation/prometheus-for-gds-paas/architecture/decisions/0002-configuration-management.md
source/documentation/prometheus-for-gds-paas/architecture/decisions/0003-use-ecs-for-initial-beta-buildout.md
source/documentation/prometheus-for-gds-paas/architecture/decisions/0004-cloudwatch-metrics.md
source/documentation/prometheus-for-gds-paas/architecture/decisions/0006-deploying-prometheus-to-private-networks-in-aws.md
source/documentation/prometheus-for-gds-paas/architecture/decisions/0008-use-of-verify-egress-proxies.md
source/documentation/prometheus-for-gds-paas/architecture/decisions/0011-sli-for-how-reliably-do-we-deliver-pages.md
source/documentation/prometheus-for-gds-paas/architecture/decisions/0012-deploy-alertmanager-to-k8s.md
source/documentation/prometheus-for-gds-paas/index.md.erb

The deadline for publishing an accessibility statement for public sector websites is 23 September 2020. As part of this project, the tech writing team is:
- reviewing all tech content that is public and uses the tech doc template
- pushing fixes where possible to increase accessibility of the content
- publishing an accessibility statement for that content
Due to compressed timescales, for some tech content, the tech writing team is doing a lightweight audit on a selection or specific page of that content. We've done a lightweight audit for the RE team manual. of [this page](https://re-team-manual.cloudapps.digital/prometheus-for-gds-paas-users.html#prometheus-for-gds-paas-service). 
This PR contains the accessibility fixes identified during the lightweight audit of this content. This …

Accessibility fixes

---

source/documentation/prometheus-for-gds-paas/index.md.erb

https://trello.com/c/vAmktonY
Documentation for the new alert (hopefully) being added in https://github.com/alphagov/prometheus-aws-configuration-beta/pull/430.
Should I add more potential causes of brokenness? Be less frank about the original screwup?

re observe alerts: add information about new RE_Observe_No_Successful_Updates alert

---

source/documentation/automate-on-call-interruptible.md

This has moved to Fargate (i.e. not EC2)

automate-on-call-interruptible: update with Hub's move to fargate

---

source/documentation/automate-on-call-interruptible.md

https://trello.com/c/2yqqA8Lb
Needed at least an excuse to be able to link to the secrets dashboard from
somewhere "official". Explained the situation hopefully omitting overly specific detail that may go out of date easily.
Also took the chance to add a couple other clarifications.

autom8 on-call/interruptible: add section on secrets over-requesting
