source/documentation/observe.md
source/index.html.md.erb

This is the first attempt at documenting the Observe interruptible process, so any comments will be welcome in order to make it easier to follow or to fill in any missing gaps or correct mistakes.

Document Observe interruptible process

---

config/tech-docs.yml

(this doesn't work so well because we have single page docs)

actually enable search

---

source/documentation/operational-tasks.md
source/operational-tasks.html.md.erb

Add instructions on adding new AWS accounts. I'm adding them to a new
operational tasks section.

Add instructions on adding new AWS accounts

---

source/documentation/observe-support.md

Runbook for the following alert:
https://github.com/alphagov/prometheus-aws-configuration-beta/pull/100

Add runbook play for `RE_Observe_Target_Down`

---

source/documentation/observe-support.md

Just a small improvement I thought could be useful based on some of the previous situations we've seen for prometheus struggling under load.

Improve potential reasons for prometheus load increase

---

source/documentation/observe-support.md

See alphagov/prometheus-aws-configuration-beta#145, which changed the
alert timings.

Tweak runbook to match alert

---

source/documentation/observe-support.md

Added in details for the new grafana down alert that is being implemented by:
https://github.com/alphagov/prometheus-aws-configuration-beta/pull/152
Paired with: @JonathanHallam

Added details for the grafana down alert.

---

source/dev-and-release-processes.html.md.erb
source/documentation/gds-aws-account-management.md
source/gds-aws-account-management-service.html.md.erb
source/joiners-and-leavers.html.md.erb
source/operational-tasks.html.md.erb
source/prometheus-for-gds-paas-users.html.md.erb
source/using-paas.html.md.erb
source/using-re-jenkins.html.md.erb

See individual commit messages

Reorg structure

---

source/documentation/prometheus-for-gds-paas/index.md

Add Dead_Mans_Switch_Constant_Alert to the Observe Team Alerts.

---

source/documentation/prometheus-for-gds-paas/index.md

this was renamed in alphagov/prometheus-aws-configuration-beta#278

rename alert to match upstream

---

.travis.yml

- We still want to check if people's docs changes build OK.

Reinstate branch builds on Travis

---

source/documentation/joiners-process.md
source/documentation/leavers-process.md
source/documentation/yubikeys.md
source/joiners-and-leavers.html.md.erb
source/yubikeys.html.md.erb

The GSP team started to enrol some YubiKeys to a service team. They have
come up with a set of instructions to make it as neat as possible for
the end user to set that up.
This should come in handy in the near future as the secret evil plan is
to start a GDS wide spread of these.
- Ask for a YubiKey
- Run through the docs
- Sanity check

Document the use of YubiKeys

---

source/documentation/yubikeys.md

yubikeys: Add troubleshooting note about Admin PIN requirement

---

source/documentation/verify.md
source/verify.html.md.erb

Creates a section for Verify because we don't have one yet.

Add DNS change docs for Verify

---

source/documentation/how-to-increase-disk-space.md
source/how-to-increase-disk-space.html.md.erb

This change adds a new page about 'How to increase disk space in Carrenza or UKCloud'.
Author: @adityapahuja

AUT-192: Add 'How to increase disk space' page

---

source/documentation/automate-on-call-interruptible.md

**Why**
The process to remove unwanted AWS accounts was not obvious.
**What**
Adding a few words to explain the outline process.

add a few words about removing team AWS accounts

---

source/documentation/prometheus-for-gds-paas/index.md.erb

prom-ec2 project is now continuously deployed no need for manual apply

update Prometheus notes to reflect reality

---

source/documentation/re-oncall-escalation-info.html.md

We have a new TAM as of a few months ago.

Update AWS Technical Account Manager

---

Gemfile
Gemfile.lock
source/documentation/prometheus-for-gds-paas/index.md.erb

Include links to the prometheus deployment pipeline in the alert runbooks.

Prometheus runbook updates

---

source/documentation/re-oncall-escalation-info.html.md

Update contact details for Carrenza (6 degrees) to include our new
Technical Account Manager and Client Service Manager.

Update contact details for Correnza (6 degrees)

---

.github/workflows/rubyandnode.yaml

Copied from https://github.com/alphagov/gds-way/pull/510

Add GitHub Action for PR builds in this repository

---

source/documentation/automate-on-call-interruptible.md

I am adding this section for absolutely no reason and it has absolutely nothing to do with me.

automate interruptable: add section on redacting build logs
